spring:
  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql:otus-library-web
    username: springuser
    password: 123

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,logfile

  endpoint:
    logfile:
      enabled: true

    health:
      show-details: when_authorized
      show-components: always

logging:
  file:
    path: logs